# Tensoren

## Import Tensorflow

In [41]:
import tensorflow as tf

## 0D-Tensor
- auch Skalar genannt

In [42]:
my_scalar = tf.constant(1, name="mein Skalar")

### Ausgabe des Skalars
- Zeigt nur die Daten innerhalb des 0D-Tensor an

In [43]:
tf.print(my_scalar)

1


#### mehr Daten über Skalar
- Zeigt relevante Informationen zum Tensor an

In [44]:
print(my_scalar)

tf.Tensor(1, shape=(), dtype=int32)


## 1D Tensor
- kann Einzelwertreihenfolgen speichern

In [45]:
tensor_1d = tf.constant([1,2,3,4])
print(tensor_1d)
tensor_1d_with_strings = tf.constant(["Hallo", "Welt", "dies", "ist", "ein 1D-Tensor!"])
print(tensor_1d_with_strings)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([b'Hallo' b'Welt' b'dies' b'ist' b'ein 1D-Tensor!'], shape=(5,), dtype=string)


### Alternative Aufgabe

In [46]:
tf.print(tensor_1d)
tf.print(tensor_1d_with_strings)

[1 2 3 4]
["Hallo" "Welt" "dies" "ist" "ein 1D-Tensor!"]


## 2D Tensor
- auch Matrix genannt
- kann indizierte (mehrspaltige) Einträge speichern

In [47]:
tensor_2d = tf.constant([[1, 2], [3, 4], [5, 6]])
print(tensor_2d)
tensor_2d_with_strings = tf.constant([["Petra", "Schmitt"], ["Max", "Mustermann"], ["John", "Doe"]])
print(tensor_2d_with_strings)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[b'Petra' b'Schmitt']
 [b'Max' b'Mustermann']
 [b'John' b'Doe']], shape=(3, 2), dtype=string)


### Alternative Ausgabe

In [48]:
tf.print(tensor_2d)
tf.print(tensor_2d_with_strings)

[[1 2]
 [3 4]
 [5 6]]
[["Petra" "Schmitt"]
 ["Max" "Mustermann"]
 ["John" "Doe"]]


## 3D-Tensor

In [49]:
tensor_3d = tf.constant([
    [[1,4], [3,8]],
    [[5,7], [9,3]]
])
tf.print(tf.rank(tensor_3d)) #  tf.rank gibt die Ordnung des Tensors wieder(1, 2, 3 oder 4D Tensor)

3


## 4D-Tensor
- z.B. ein Video
- Reihenfolge von Bildern (3D-Tensor)

## Numpy Strukturen in Tensorflow

In [50]:
import numpy as np

np_array = np.arange(0, 5, step=0.5)
tensor_from_numpy = tf.constant(np_array, name="converted")
print("Eine Numpy-Struktur kann in einen Tensor umgewandelt werden:", tensor_from_numpy)
print("und wieder zurück in eine NumPy-Struktur:", tensor_from_numpy.numpy())

Eine Numpy-Struktur kann in einen Tensor umgewandelt werden: tf.Tensor([0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5], shape=(10,), dtype=float64)
und wieder zurück in eine NumPy-Struktur: [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


## Bilder laden mit Numy und Tensorflow

In [51]:
from PIL import Image

# Alternative 1: mit Pillow
print("== Alternative 1 ==")
img1 = Image.open("cat.jpg")
img1.load()
img_data = np.asarray( img1, dtype="int32" )
img_tensor = tf.convert_to_tensor(img_data, dtype=tf.int32)
tf.print(img_tensor)
print("Rank des Tensors: {}".format(tf.rank(img_tensor)))

== Alternative 1 ==
[[[183 205 219]
  [184 206 220]
  [186 208 222]
  ...
  [221 224 229]
  [221 224 229]
  [221 224 229]]

 [[183 205 219]
  [184 206 220]
  [186 208 222]
  ...
  [220 223 228]
  [220 223 228]
  [220 223 228]]

 [[183 205 219]
  [184 206 220]
  [185 207 221]
  ...
  [221 224 229]
  [221 224 229]
  [221 224 229]]

 ...

 [[210 208 213]
  [210 208 213]
  [210 208 213]
  ...
  [208 206 207]
  [208 206 207]
  [208 206 207]]

 [[210 208 213]
  [210 208 213]
  [210 208 213]
  ...
  [208 206 207]
  [208 206 207]
  [208 206 207]]

 [[210 208 213]
  [210 208 213]
  [210 208 213]
  ...
  [208 206 207]
  [208 206 207]
  [208 206 207]]]
Rank des Tensors: 3


In [52]:
# Alternative 2: Mit tf.image.decode.jpeg()
print("== Alternative 2 ==")
img2 = tf.image.decode_jpeg(tf.io.read_file("cat.jpg"))
print("Rank des Tensors: {}".format(tf.rank(img2)))

== Alternative 2 ==
Rank des Tensors: 3


In [53]:
# Alternative 3
print("== Alternative 3 ==")
img3 = tf.image.decode_image(tf.io.read_file("cat.jpg"))
print("Rank des Tensors: {}".format(tf.rank(img3)))
print("Shape des Bildes: {}".format(tf.shape(img3)))
print("RGB-Werte vom Pixel (x:0, y:0)", img3[0][0])

== Alternative 3 ==
Rank des Tensors: 3
Shape des Bildes: [1163 2067    3]
RGB-Werte vom Pixel (x:0, y:0) tf.Tensor([183 205 219], shape=(3,), dtype=uint8)


## Variablen in Tensorflow
- kann genutzt werden um Parameter eines Modells während des Trainings zu verändern oder Werte von Tensoren zu speichern
- kann über Operationen gesetzt und verändert werden

In [54]:
my_tensor = tf.Variable([[1, 2, 3], [4, 5, 6]])

# Erstes Beispiel
t = np.array([2])

# Equivalent zu my_tensor = my_tensor * 2
my_tensor = my_tensor * t
my_tensor = tf.square(my_tensor) / 4
my_tensor = my_tensor - 1
print("Ausgabe Beispiel 1:")
print(my_tensor)
tf.print(my_tensor)

Ausgabe Beispiel 1:
tf.Tensor(
[[ 0.  3.  8.]
 [15. 24. 35.]], shape=(2, 3), dtype=float64)
[[0 3 8]
 [15 24 35]]


In [55]:
my_tensor = tf.Variable([[1, 2, 3], [4, 5, 6]])
my_second_tensor = my_tensor.assign([[0, 0, 7], [0, 0, 8]]) #  kann nur ausgeführt werden wenn der Datentyp übereinstimmt
print("Ausgabe Beispiel 2:")
tf.print(my_second_tensor)

Ausgabe Beispiel 2:
[[0 0 7]
 [0 0 8]]


## Graphen
- Set aus mathematischen Funktionen, die mit Knoten (Edges) verbunden sind (siehe Algorithmen/Graphenprobleme)
- werden durch optimierten C++ Code ausgeführt
- entscheidet ob Operation auf CPU oder GPU ausgeführt wird
- Tensorflow 2 kann auf Graphen verzichtet werden

### Konzept

In [56]:
a = tf.Variable(3.0)
b = tf.Variable(4.0)
c = tf.Variable(1.0)
d = tf.Variable(2.0)

x_1 = tf.multiply(a, b, "Multiplikation")  # 12
x_2 = tf.add(c, d, "Addieren")  # 3
x_3 = tf.subtract(x_1, x_2, "Subtrahieren")  # 9
result = tf.sqrt(x_3, "Wurzel")  # 3
print("Ergebnis der Berechnung: {}".format(result.numpy()))

Ergebnis der Berechnung: 3.0


### Graphen in Tensorflow 2.0

In [57]:
tf.summary.trace_on(graph=True, profiler=True)

@tf.function
def my_function(a,b,c,d):
    x_1 = tf.multiply(a, b, "Multiplikation")  # 12
    x_2 = tf.add(c, d, "Addieren")  # 3
    x_3 = tf.subtract(x_1, x_2, "Subtrahieren")  # 9
    result = tf.sqrt(x_3, "Wurzel")  # 3
    return result

res = my_function(a,b,c,d)
print("Ergebnis der Berechnung: {}".format(result.numpy()))

Ergebnis der Berechnung: 3.0


#### Code der von Autograph der Tensorflow 2.0 Bibliothek generiert wurde

In [58]:
print(tf.autograph.to_code(my_function.python_function))

def tf__my_function(a, b, c, d):
    with ag__.FunctionScope('my_function', 'fscope', ag__.ConversionOptions(recursive=True, user_requested=True, optional_features=(), internal_convert_user_code=True)) as fscope:
        do_return = False
        retval_ = ag__.UndefinedReturnValue()
        x_1 = ag__.converted_call(ag__.ld(tf).multiply, (ag__.ld(a), ag__.ld(b), 'Multiplikation'), None, fscope)
        x_2 = ag__.converted_call(ag__.ld(tf).add, (ag__.ld(c), ag__.ld(d), 'Addieren'), None, fscope)
        x_3 = ag__.converted_call(ag__.ld(tf).subtract, (ag__.ld(x_1), ag__.ld(x_2), 'Subtrahieren'), None, fscope)
        result = ag__.converted_call(ag__.ld(tf).sqrt, (ag__.ld(x_3), 'Wurzel'), None, fscope)
        try:
            do_return = True
            retval_ = ag__.ld(result)
        except:
            do_return = False
            raise
        return fscope.ret(retval_, do_return)



### Visualisierung von Graphen

In [59]:
tf.summary.trace_on(graph=True, profiler=True)

writer = tf.summary.create_file_writer("./logs")
with writer.as_default():
    tf.summary.trace_export(
        name="export",
        step=0,
        profiler_outdir="./logs"
    )

### Benutzung der CPU bzw. GPU

In [60]:
tf.debugging.set_log_device_placement(True)

def get_GPU_CPU_details():
    print("GPU vorhanden?", tf.test.is_gpu_available())
    print("Devices:", tf.config.experimental.list_physical_devices())

get_GPU_CPU_details()

GPU vorhanden? True
Devices: [PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
